### ISSUE TITLE
Exception when processing operator $in

### ISSUE THREAD

**Issue by anhldbk** [crcn/sift.js#112]
I tried to run the below code:

```js
var sift = require('sift')
var res = sift({ location: { $in: ['Costa Rica','Brazil']  }  }, { name: 'Craig', location: 'Brazil'  });
console.log(res)
```
But I've got an exception of: 

```
λ bigsonata alpha → node test.js
/home/bigsonata/projects/alpha/node_modules/sift/sift.js:465
      return array.filter(filter);
                   ^

TypeError: array.filter is not a function
    at sift (/home/bigsonata/projects/alpha/node_modules/sift/sift.js:465:20)
    at Object.<anonymous> (/home/bigsonata/projects/alpha/test.js:2:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

Here is my environment:

```sh
λ bigsonata alpha → cat package.json | grep sift
    "sift": "^3.2.6"
λ bigsonata test → node -v
v6.9.1

```

**Comment by anhldbk** [comment]
Solved!
