### ISSUE TITLE
Throws Error When Comparing `ObjectId`s

### ISSUE THREAD

**Issue by bendytree** [crcn/sift.js#47]
I'm using `sift.js` to do server-side filtering of documents I fetched from MongoDB. When I try to compare `ObjectId`s, sift throws an error. Here's a simplified example:

    var ObjectId = require("mongoose").Types.ObjectId;
    var sift = require("sift");
    var x = "5490b86e7ba2f60675390146";
    var filter = { id : ObjectId(x) };
    var items = [{ id : ObjectId(x) }];
    var results = sift(filter, items); //error

Here's the error:

    /web/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/objectid.js:69
      for (var i = 0; i < this.id.length; i++) {
                                 ^
    TypeError: Cannot read property 'length' of undefined
        at ObjectID.toHexString [as test] (/web/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/objectid.js:69:30)
        at Object._testers.testers.$eq [as e] (/web/node_modules/sift/sift.js:177:23)
        at priority.priority (/web/node_modules/sift/sift.js:51:24)
        at Object._testers.testers.$trav [as e] (/web/node_modules/sift/sift.js:360:16)
        at priority.priority (/web/node_modules/sift/sift.js:51:24)
        at Object._testers.testers.$trav [as e] (/web/node_modules/sift/sift.js:360:16)
        at priority.priority (/web/node_modules/sift/sift.js:51:24)
        at Object.stmt.priority (/web/node_modules/sift/sift.js:140:18)
        at self (/web/node_modules/sift/sift.js:469:33)
        at sift (/web/node_modules/sift/sift.js:522:23)

**Comment by crcn** [comment]
Exception is resolved. However, the only way to compare objectIds is to do something like this:

```javascript

// won't work
sift(ObjectID("54dd5546b1d296a54d152e84"),[ObjectID(),ObjectID("54dd5546b1d296a54d152e84")]); // []

// works
sift(function (value) {
  return String(value) === "54dd5546b1d296a54d152e84";
}, [ObjectID(),ObjectID("54dd5546b1d296a54d152e84")]); // [ObjectID("54dd5546b1d296a54d152e84")]

// works
sift({ $where: "this.id === '54dd5546b1d296a54d152e84' },  [{ id: ObjectID("54dd5546b1d296a54d152e84") }]); // [ObjectID("54dd5546b1d296a54d152e84")]
```
